version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            - discovery.type=single-node
        networks:
            - logging-network
            
    logstash:
        build: ./logstash
        depends_on:
            - elasticsearch
        ports:
            - 12201:12201/udp
        networks:
            - logging-network
            
    kibana:
        image: docker.elastic.co/kibana/kibana:7.4.2
        depends_on:
            - logstash
        ports:
            - 5601:5601
        networks:
            - logging-network

networks:
        logging-network:
            driver: bridge
